"""
Simulated deal data based on real KBCM transactions.
US Fertility Enterprises – $1.05B Senior Secured Credit Facilities (2024)
Apex Clean Energy – $1.05B Senior Secured Credit Facilities (2025)
"""

from datetime import date

DEALS = {
    "USF-2024": {
        "deal_id": "USF-2024",
        "borrower": "US Fertility Enterprises",
        "industry": "Healthcare – Fertility Services",
        "sponsor": "Amulet Capital Partners",
        "purpose": "LBO Refinancing & Growth Capital",
        "total_facility": 1_050_000_000,
        "lead_arranger": "KeyBanc Capital Markets (KBCM)",
        "bookrunners": ["KeyBanc Capital Markets", "Truist Securities", "Regions Capital Markets"],
        "administrative_agent": "KeyBank National Association",
        "deal_rating": "B2 / B",
        "announcement_date": date(2024, 3, 15),
        "close_date": date(2024, 4, 30),
        "tranches": {
            "Revolving Credit Facility": {
                "type": "Revolver",
                "amount": 150_000_000,
                "currency": "USD",
                "tenor": "5 years",
                "maturity_date": date(2029, 4, 30),
                "pricing": {
                    "index": "SOFR",
                    "spread_bps": 400,
                    "floor_bps": 0,
                    "oid": None,
                    "commitment_fee_bps": 50,
                    "drawn_margin_bps": 400,
                },
                "status": "Funded",
                "lenders": [
                    {"name": "KeyBank National Association", "hold_mm": 40.0, "role": "Agent / Lender"},
                    {"name": "Truist Bank", "hold_mm": 30.0, "role": "Lender"},
                    {"name": "Regions Bank", "hold_mm": 25.0, "role": "Lender"},
                    {"name": "Fifth Third Bank", "hold_mm": 25.0, "role": "Lender"},
                ],
                "flex_status": "Priced tight – spread flexed in 25bps from initial talk",
                "notes": "Subject to springing maturity if TLB outstanding 91 days prior to TLB maturity.",
            },
            "Term Loan B": {
                "type": "TLB",
                "amount": 500_000_000,
                "currency": "USD",
                "tenor": "7 years",
                "maturity_date": date(2031, 4, 30),
                "pricing": {
                    "index": "SOFR",
                    "spread_bps": 425,
                    "floor_bps": 100,
                    "oid": 99.0,
                    "commitment_fee_bps": None,
                    "drawn_margin_bps": 425,
                },
                "status": "Funded",
                "lenders": [
                    {"name": "Blackstone Credit", "hold_mm": 150.0, "role": "Anchor Lender"},
                    {"name": "Ares Management", "hold_mm": 125.0, "role": "Lender"},
                    {"name": "Blue Owl Capital", "hold_mm": 100.0, "role": "Lender"},
                    {"name": "HPS Investment Partners", "hold_mm": 90.0, "role": "Lender"},
                    {"name": "Golub Capital", "hold_mm": 75.0, "role": "Lender"},
                    {"name": "Antares Capital", "hold_mm": 60.0, "role": "Lender"},
                    {"name": "Various CLOs / Funds", "hold_mm": 225.0, "role": "Syndicate"},
                ],
                "flex_status": "No flex – priced at initial talk (SOFR+425, OID 99)",
                "notes": "101 soft call protection for 6 months. 1% annual amortization.",
            },
            "Letter of Credit Facility": {
                "type": "DDTL",
                "amount": 400_000_000,
                "currency": "USD",
                "tenor": "7 years",
                "maturity_date": date(2031, 4, 30),
                "pricing": {
                    "index": "SOFR",
                    "spread_bps": 425,
                    "floor_bps": 100,
                    "oid": 99.0,
                    "commitment_fee_bps": 212,  # 50% of margin
                    "drawn_margin_bps": 425,
                },
                "status": "Partially Drawn",
                "availability_period_end": date(2025, 4, 30),
                "drawn_amount": 60_000_000,
                "lenders": [
                    {"name": "Blackstone Credit", "hold_mm": 35.0, "role": "Anchor Lender"},
                    {"name": "Ares Management", "hold_mm": 30.0, "role": "Lender"},
                    {"name": "Blue Owl Capital", "hold_mm": 25.0, "role": "Lender"},
                    {"name": "Golub Capital", "hold_mm": 20.0, "role": "Lender"},
                    {"name": "Antares Capital", "hold_mm": 15.0, "role": "Lender"},
                ],
                "flex_status": "Same as TLB – priced in line",
                "notes": "18-month availability window for acquisitions. Commitment fee on undrawn.",
            },
        },
        "milestones": [
            {"milestone": "Mandate Awarded", "tranche": "All", "due_date": date(2024, 3, 15), "status": "Complete", "owner": "KBCM Origination"},
            {"milestone": "CIM / Bank Book Distributed", "tranche": "All", "due_date": date(2024, 3, 22), "status": "Complete", "owner": "KBCM Syndicate"},
            {"milestone": "Lender Meetings", "tranche": "TLB / DDTL", "due_date": date(2024, 3, 28), "status": "Complete", "owner": "KBCM Syndicate"},
            {"milestone": "Commitments Due", "tranche": "Revolver", "due_date": date(2024, 4, 5), "status": "Complete", "owner": "KBCM Agency"},
            {"milestone": "Allocations Finalized", "tranche": "TLB", "due_date": date(2024, 4, 10), "status": "Complete", "owner": "KBCM Syndicate"},
            {"milestone": "Credit Agreement Executed", "tranche": "All", "due_date": date(2024, 4, 25), "status": "Complete", "owner": "Legal – Latham & Watkins"},
            {"milestone": "Closing & Funding", "tranche": "All", "due_date": date(2024, 4, 30), "status": "Complete", "owner": "KBCM Agency"},
            {"milestone": "DDTL Draw #1", "tranche": "DDTL", "due_date": date(2024, 9, 15), "status": "Complete", "owner": "US Fertility / Agent"},
            {"milestone": "DDTL Availability Period End", "tranche": "DDTL", "due_date": date(2025, 4, 30), "status": "Upcoming", "owner": "KBCM Agency"},
            {"milestone": "Annual Compliance Certificate", "tranche": "All", "due_date": date(2025, 5, 30), "status": "Upcoming", "owner": "Borrower / Agent"},
        ],
        "followups": [
            {"party": "US Fertility CFO", "action": "Deliver Q1 2025 Compliance Certificate", "due_date": date(2025, 4, 15), "priority": "High", "done": False},
            {"party": "Blackstone Credit", "action": "Confirm DDTL draw intention before availability period end", "due_date": date(2025, 4, 1), "priority": "High", "done": False},
            {"party": "KBCM Agency Desk", "action": "Send DDTL availability period expiry notice to all lenders", "due_date": date(2025, 3, 30), "priority": "Medium", "done": False},
            {"party": "Latham & Watkins", "action": "Confirm no covenant cure events triggered in Q4 2024", "due_date": date(2025, 3, 20), "priority": "Medium", "done": True},
            {"party": "Truist Bank", "action": "Updated KYC / AML refresh for revolver renewal", "due_date": date(2025, 6, 1), "priority": "Low", "done": False},
        ],
    },

    "ACE-2025": {
        "deal_id": "ACE-2025",
        "borrower": "Apex Clean Energy",
        "industry": "Renewable Energy – Wind & Solar",
        "sponsor": "Stonepeak Infrastructure Partners",
        "purpose": "Project Finance – Portfolio Expansion",
        "total_facility": 1_050_000_000,
        "lead_arranger": "KeyBanc Capital Markets (KBCM)",
        "bookrunners": ["KeyBanc Capital Markets", "BMO Capital Markets", "MUFG"],
        "administrative_agent": "KeyBank National Association",
        "deal_rating": "BB- / Ba3",
        "announcement_date": date(2025, 9, 10),
        "close_date": date(2025, 11, 14),
        "tranches": {
            "Term Loan": {
                "type": "TLA",
                "amount": 500_000_000,
                "currency": "USD",
                "tenor": "5 years",
                "maturity_date": date(2030, 11, 14),
                "pricing": {
                    "index": "SOFR",
                    "spread_bps": 275,
                    "floor_bps": 0,
                    "oid": 99.5,
                    "commitment_fee_bps": None,
                    "drawn_margin_bps": 275,
                },
                "status": "Funded",
                "lenders": [
                    {"name": "KeyBank National Association", "hold_mm": 100.0, "role": "Agent / Lender"},
                    {"name": "BMO Bank", "hold_mm": 90.0, "role": "Lender"},
                    {"name": "MUFG Bank", "hold_mm": 90.0, "role": "Lender"},
                    {"name": "ING Capital", "hold_mm": 75.0, "role": "Lender"},
                    {"name": "Société Générale", "hold_mm": 70.0, "role": "Lender"},
                    {"name": "Other Banks", "hold_mm": 75.0, "role": "Syndicate"},
                ],
                "flex_status": "Spread flexed wide 25bps – energy market volatility",
                "notes": "ESG-linked margin ratchet: -10bps if renewable capacity targets met annually.",
            },
            "Letter of Credit Facility": {
                "type": "LC Facility",
                "amount": 400_000_000,
                "currency": "USD",
                "tenor": "5 years",
                "maturity_date": date(2030, 11, 14),
                "pricing": {
                    "index": "N/A",
                    "spread_bps": 200,
                    "floor_bps": None,
                    "oid": None,
                    "commitment_fee_bps": 40,
                    "drawn_margin_bps": 200,
                },
                "status": "Active – Partially Utilized",
                "lenders": [
                    {"name": "KeyBank National Association", "hold_mm": 120.0, "role": "LC Issuer / Agent"},
                    {"name": "BMO Bank", "hold_mm": 100.0, "role": "LC Participant"},
                    {"name": "MUFG Bank", "hold_mm": 100.0, "role": "LC Participant"},
                    {"name": "ING Capital", "hold_mm": 80.0, "role": "LC Participant"},
                ],
                "flex_status": "Priced at initial talk",
                "notes": "Supports PPA and interconnection obligations. fronting fee 12.5bps.",
            },
            "Revolving Credit Facility": {
                "type": "Revolver",
                "amount": 150_000_000,
                "currency": "USD",
                "tenor": "5 years",
                "maturity_date": date(2030, 11, 14),
                "pricing": {
                    "index": "SOFR",
                    "spread_bps": 250,
                    "floor_bps": 0,
                    "oid": None,
                    "commitment_fee_bps": 37,
                    "drawn_margin_bps": 250,
                },
                "status": "Undrawn",
                "lenders": [
                    {"name": "KeyBank National Association", "hold_mm": 60.0, "role": "Agent / Lender"},
                    {"name": "BMO Bank", "hold_mm": 45.0, "role": "Lender"},
                    {"name": "MUFG Bank", "hold_mm": 45.0, "role": "Lender"},
                ],
                "flex_status": "Priced at initial talk",
                "notes": "Working capital facility. Clean-down requirement: 30 consecutive days undrawn per year.",
            },
        },
        "milestones": [
            {"milestone": "Mandate Awarded", "tranche": "All", "due_date": date(2025, 9, 10), "status": "Complete", "owner": "KBCM Origination"},
            {"milestone": "Bank Book Distributed", "tranche": "All", "due_date": date(2025, 9, 18), "status": "Complete", "owner": "KBCM Syndicate"},
            {"milestone": "Lender Meetings", "tranche": "TL / Revolver", "due_date": date(2025, 9, 25), "status": "Complete", "owner": "KBCM Syndicate"},
            {"milestone": "Commitments Received", "tranche": "All", "due_date": date(2025, 10, 10), "status": "Complete", "owner": "KBCM Agency"},
            {"milestone": "Allocations Finalized", "tranche": "All", "due_date": date(2025, 10, 20), "status": "Complete", "owner": "KBCM Syndicate"},
            {"milestone": "Credit Agreement Signed", "tranche": "All", "due_date": date(2025, 11, 10), "status": "Complete", "owner": "Legal – Simpson Thacher"},
            {"milestone": "Closing & Funding", "tranche": "All", "due_date": date(2025, 11, 14), "status": "Complete", "owner": "KBCM Agency"},
            {"milestone": "First ESG Reporting Period", "tranche": "TL", "due_date": date(2026, 5, 1), "status": "Upcoming", "owner": "Apex / Agent"},
            {"milestone": "Annual Lender Call", "tranche": "All", "due_date": date(2026, 6, 1), "status": "Upcoming", "owner": "KBCM Agency"},
        ],
        "followups": [
            {"party": "Apex Clean Energy IR", "action": "Provide renewable capacity build-out update for ESG margin ratchet assessment", "due_date": date(2026, 4, 1), "priority": "High", "done": False},
            {"party": "ING Capital", "action": "Confirm LC participation renewal terms", "due_date": date(2026, 3, 15), "priority": "Medium", "done": False},
            {"party": "Simpson Thacher", "action": "Send annual covenant compliance summary to syndicate", "due_date": date(2026, 3, 30), "priority": "Medium", "done": False},
            {"party": "KBCM Agency Desk", "action": "Schedule annual lender update call with Apex management", "due_date": date(2026, 5, 15), "priority": "Low", "done": False},
            {"party": "Stonepeak Infrastructure", "action": "Confirm no change of control triggers from fund rebalancing", "due_date": date(2026, 4, 30), "priority": "Low", "done": True},
        ],
    },
}
